config/routes.rb
Case::Application.routes.draw do

scope 'tracks' do

resources :courtstations do
resources :batches
end

resources :sms

get 'courtstations:id', to: 'courtstations#stationmovements', as: :station

resources :courtstations do
  resources :casefiles do
 collection do
    match 'search' => 'casefiles#search', via: [:get, :post], as: :search
  end
    resources :movements do
  end
end
end

  devise_for :users

  resources :judicial_officers

  devise_for :admins

  get "dashboard/audit"
get "dashboard/login"
get "admin/index"
get "dashboard/index"
get "dashboard/useractivity"
get "dashboard/mini_dashboard"
get "dashboard/caselistreport"
get "dashboard/casestatusreports"

   
 root :to => 'courtstations#index'

end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
 def audit
 	@changes = Audit.trackertype.order_latest
 end 
 def mini_dashboard

end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_movements.erb
<div id="filterrific_results">
 <div>
    <%= page_entries_info movements%>
  </div>

<table border "2" class = "display" >
  <tr>
    <th>Case Number</th>
 <th>Date Out</th>
    <th>From</th>
    <th>To</th>
    <th>Taken by</th>
    <th>Reason</th>
    <th>Officer Taking Action</th>
	<th>Date In</th>
	<th>Remarks</th>
    <th>Results</th>
    <th>Date of result</th>
    <th>Record Created By</th>
    <th>Record Updated Last By</th>

    
  </tr>

<% @movements.each do |tracker| %>
  <tr>
    <td><%= tracker.casefile.casenumber%></td>
    <td><%= tracker.created_at %></td>
    <td><%= tracker.from %></td>
    <td><%= tracker.to %></td>
    <td><%= tracker.takenby %></td>
    <td><%= tracker.reason %></td>
    <td><%= tracker.officer %></td>
	<td><%= tracker.datein %></td>
	<td><%= tracker.remarks %></td>
    <td><%= tracker.results %></td>
    <td><%= tracker.dateofresult %></td>
    <td><%= tracker.recordcreatedby%></td>
    <td><%= tracker.recordupdatedby%></td>
    
  </tr>
<% end %>
</table>
</div>
<%= will_paginate movements %>
<%=link_to_function image_tag('/assets/back.jpeg') + "Back", "history.back()"%>

app/views/dashboard/audit.erb
<div id="filterrific_results">
</table>
<table border "2" class = "display" >
  <tr>
    <th>User Name</th>
    <th>User PJ</th>
    <th>User Station</th>
    <th>Modified File</th>
    <th>Type</th>
    <th>Action</th>
    <th>Changes</th>
    <th>IP Address</th>
    <th>Changes Date and Time</th>
  </tr>
<% @changes.each do |change| %>
  <tr>
    <td><%= change.user.username %></td>
    <td><%= change.user.pj %></td>
    <td><%= change.user.station %></td>
    <th><%= change.auditable_id%></th>
    <td><%= change.auditable_type %></td>
    <td><%= change.action %></td>
    <td><%= change.audited_changes %></td>
    <td><%= change.remote_address %></td>
    <td><%= change.created_at %></td>
  </tr>
<% end %>
</table>
</div>

app/views/dashboard/caselistreport.erb
<%= form_for @filterrific do |f| %>
<div id ="filters">
<table >
<tr>
   <td>Case Status </td>
  <td>Type of Case </td>
 <td>Year Filed</td>
 
</tr>
     <td><%= f.select(:casestatus,options_for_select([["Any",""],["Pending", "Pending"],["Concluded", "Concluded"]]),class: 'filterrific-periodically observed') %></td>


     <td><%= f.select(:casetype,Casetype.options_for_casetype,{ :include_blank => '- Any -' },class: 'filterrific-periodically observed') %></td>


     <td><%= f.select(:filedyear,options_for_select((1980...Time.now.year.next).sort.reverse),{ :include_blank => '- Any -' } ,class: 'filterrific-periodically observed') %></tr>

    
</table>
</div>
<%= render_filterrific_spinner %>

<% end %>
<%= render(
  partial: 'dashboard/list',
locals: { casefiles: @casefiles }
) %>

app/views/dashboard/caselistreport.js.erb
<% js = escape_javascript(render(partial: 'dashboard/list',:locals => { :casefiles => @casefiles})) %>
$("#filterrific_results").html("<%= js %>");

app/views/dashboard/casestatusreports.erb
<h1>Reports</h1/>

<div id = "reports" >

<table border="3" class = "display" >
<tr>
<th>Type of Case</th>
<th>Case Count</th>


</tr>
<% @casecount.each do |a,b| %>
<tr>
<td><%=a%></td>
<td><%=b%></td>

<%end%>

</tr>
</table>

</div>
</div>

app/views/dashboard/filemovements.erb
<%= form_for @filterrific do |f| %>
<div id ="filters">
<table >
<tr>
<td> File Location </td>
<td> Officer Taking Action  </td>
<td> File Taken By </td>
<td> Date Taken </td>
<td> User </td>
<td> Court Station </td>
</tr>
<tr>
  <td> <%= f.select:filelocation,Movement.options_for_filetakento ,{ :include_blank => '- Any -' },class: 'filterrific-periodically observed' %></td>
  <td><%= f.select :officertakingaction,Movement.options_for_officertakingaction,{ :include_blank => '- Any -' },class: 'filterrific-periodically observed' %></td>
 <td>    <%= f.select:filetakenby,Movement.options_for_filetakenby,{ :include_blank => '- Any -' },class: 'filterrific-periodically observed' %></td>
 <td><%= f.text_field:with_created_at_gte, :id => "datepicker",:autocomplete => 'off',class: 'datepicker',:size => "10x3" %></td>
<td><%= f.select:user,Movement.options_for_user,{ :include_blank => '- Any -' },class: 'filterrific-periodically observed' %></td>
<td><%= f.text_field:courtstation,:size => "10x3",:value =>current_user.station,:readonly => true,class: 'filterrific-periodically observed' %></td>
</tr>
</table>
</div>
<% end %>
<%= render(
  partial: 'dashboard/movements',
locals: { movements: @movements }
) %>

app/views/dashboard/filemovements.js.erb
<% js = escape_javascript(render(partial: 'dashboard/movements',:locals => { :movements => @movements})) %>
$("#filterrific_results").html("<%= js %>");
$(document).ready(function() {
    $(".datepicker").datepicker({dateFormat: "yy-mm-dd"});
});

app/views/dashboard/index.erb
<h1>Dashboard login</h1>
<h2>Welcome</h2>
<div id = "dashboard" >


<%= link_to image_tag('/assets/caseregister.png') + 'Cases Register',dashboard_caselistreport_path%>
<%= link_to image_tag('/assets/filemovement.png') + 'File Movements',dashboard_filemovements_path%>
<%= link_to image_tag('/assets/casestatus.png') + 'Case Status',dashboard_casestatusreports_path%>

<%= link_to image_tag('/assets/user.png') + 'User Activity',dashboard_useractivity_path%>
<%= link_to image_tag('/assets/audit.png') + 'Audit Trail',dashboard_audit_path%>

<!-- uer
<%= link_to image_tag('/assets/bringup.png') + 'Bring Up'%>#
<%= link_to image_tag('/assets/archive.png') + 'Archive'%>#
-->
</div>

</div>

app/views/dashboard/login.html.erb
<h1>Dashboard login</h1>
<h2>Welcome</h2>
<div id = "dashboard" >


<p>Type the Case Number Here<p/>
<%= image_tag "search.png" %>
<%= form_tag(courtstations_casefile_search_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Cases" %>
  <%= submit_tag "Search", :casenumber => nil %>
<% end %>
<div id = "dashboardicons" >


<%= link_to image_tag('/assets/caseregister.png') + 'Cases Register'%>
<%= link_to image_tag('/assets/filemovement.png') + 'File Movements'%>
<%= link_to image_tag('/assets/casestatus.png') + 'Case Status'%>

<%= link_to image_tag('/assets/user.png') + 'Activity'%>
<%= link_to image_tag('/assets/audit.png') + 'Audit Trail'%>


</div>

</div>

app/views/dashboard/minidashboard.erb
<%= form_for @filterrific do |f| %>
<div id ="filters">
<table >
<tr>
<td> File Location </td>
<td> Officer Taking Action  </td>
<td> File Taken By </td>
<td> Date Taken </td>
<td> User </td>
<td> Court Station </td>
</tr>
<tr>
  <td> <%= f.select:filelocation,Movement.options_for_filetakento ,{ :include_blank => '- Any -' },class: 'filterrific-periodically observed' %></td>
  <td><%= f.select :officertakingaction,Movement.options_for_officertakingaction,{ :include_blank => '- Any -' },class: 'filterrific-periodically observed' %></td>
 <td>    <%= f.select:filetakenby,Movement.options_for_filetakenby,{ :include_blank => '- Any -' },class: 'filterrific-periodically observed' %></td>
 <td><%= f.text_field:with_created_at_gte, :id => "datepicker",:autocomplete => 'off',class: 'datepicker',:size => "10x3" %></td>
<td><%= f.select:user,Movement.options_for_user,{ :include_blank => '- Any -' },class: 'filterrific-periodically observed' %></td>
<td><%= f.text_field:courtstation,:size => "10x3",:value =>current_user.station,:readonly => true,class: 'filterrific-periodically observed' %></td>
</tr>
</table>
</div>
<% end %>
<%= render(
  partial: 'dashboard/movements',
locals: { movements: @movements }
) %>

app/views/dashboard/useractivity.erb
<h1>User Activity</h1/>

<div id = "reports" >

<table border="3" class = "display" >
<tr>
<th>User and Date</th>
<th>Activity Count</th>


</tr>
<% @movementcount.each do |a,b| %>
<tr>
<td><%=a%></td>
<td><%=b%></td>

<%end%>

</tr>
</table>

</div>
</div>