config/routes.rb
Case::Application.routes.draw do

scope 'tracks' do

resources :courtstations do
resources :batches
end

resources :sms

get 'courtstations:id', to: 'courtstations#stationmovements', as: :station

resources :courtstations do
  resources :casefiles do
 collection do
    match 'search' => 'casefiles#search', via: [:get, :post], as: :search
  end
    resources :movements do
  end
end
end

  devise_for :users

  resources :judicial_officers

  devise_for :admins

  get "dashboard/audit"
get "dashboard/login"
get "admin/index"
get "dashboard/index"
get "dashboard/useractivity"
get "dashboard/mini_dashboard"
get "dashboard/caselistreport"
get "dashboard/casestatusreports"

   
 root :to => 'courtstations#index'

end
end

app/views/admin/index.erb
<h1>Admin Dashboard</h1>
<div id = "dashboard" >


<%= link_to image_tag('/assets/calender.png') + 'Cases Register',dashboard_caselistreport_path%>
<%= link_to image_tag('/assets/calender.png') + 'File Movements',dashboard_filemovements_path%>
<%= link_to image_tag('/assets/calender.png') + 'Case Status',dashboard_casestatusreports_path%>

<%= link_to image_tag('/assets/calender.png') + 'User Activity',dashboard_useractivity_path%>
<%= link_to image_tag('/assets/calender.png') + 'New Outcome',new_caseoutcome_path%>
<%= link_to image_tag('/assets/calender.png') + 'New Officer',new_judicial_officer_path%>
<%= link_to image_tag('/assets/calender.png') + 'New File Location',new_filelocation_path%>
<%= link_to image_tag('/assets/calender.png') + 'New Movement Reason',new_movementreason_path%>
<%= link_to image_tag('/assets/calender.png') + 'New Adjournment Reason',new_adjournmentreason_path%>
<%= link_to image_tag('/assets/calender.png') + 'New Outcome',new_caseoutcome_path%>
<%= link_to image_tag('/assets/calender.png') + 'New User',new_user_registration_path%>
<%= link_to image_tag('/assets/calender.png') + 'New Case Type',new_casetype_path%>

<!-- uer
<%= link_to image_tag('/assets/bringup.png') + 'Bring Up'%>#
<%= link_to image_tag('/assets/archive.png') + 'Archive'%>#
-->
</div>

</div>