config/routes.rb
Case::Application.routes.draw do

scope 'tracks' do

resources :courtstations do
resources :batches
end

resources :sms

get 'courtstations:id', to: 'courtstations#stationmovements', as: :station

resources :courtstations do
  resources :casefiles do
 collection do
    match 'search' => 'casefiles#search', via: [:get, :post], as: :search
  end
    resources :movements do
  end
end
end

  devise_for :users

  resources :judicial_officers

  devise_for :admins

  get "dashboard/audit"
get "dashboard/login"
get "admin/index"
get "dashboard/index"
get "dashboard/useractivity"
get "dashboard/mini_dashboard"
get "dashboard/caselistreport"
get "dashboard/casestatusreports"

   
 root :to => 'courtstations#index'

end
end

app/models/courtstation.rb
class Courtstation < ActiveRecord::Base
  has_many :batches
  has_many :fileactions
  has_many :casefiles
  has_many :movements, through: :casefiles
  attr_accessible :name, :typeofcourt

def self.option_for_courtstations
self.pluck(:name)
end
end

app/controllers/courtstations_controller.rb
class CourtstationsController < ApplicationController
 before_filter :authenticate_user!
#before_filter :redirect_to_station_path
  # GET /courtstations
  # GET /courtstations.json
 

def search
end



 def stationmovements
	@courtstation = Courtstation.find(params[:id])
		@movesearch =@courtstation.movements
		if params[:q].blank?
		@q = @movesearch.none.ransack # so you have a ransack search
		else
		@q = @movesearch.ransack(params[:q])
		end
		@stationmovements =@q.result
end


def index

    @courtstations = Courtstation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courtstations }
    end
  end

  # GET /courtstations/1
  # GET /courtstations/1.json
  def show
    @courtstation = Courtstation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @courtstation }
    end
  end

  # GET /courtstations/new
  # GET /courtstations/new.json
  def new
    @courtstation = Courtstation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @courtstation }
    end
  end

  # GET /courtstations/1/edit
  def edit
    @courtstation = Courtstation.find(params[:id])
  end

  # POST /courtstations
  # POST /courtstations.json
  def create
    @courtstation = Courtstation.new(params[:courtstation])

    respond_to do |format|
      if @courtstation.save
        format.html { redirect_to @courtstation, notice: 'Courtstation was successfully created.' }
        format.json { render json: @courtstation, status: :created, location: @courtstation }
      else
        format.html { render action: "new" }
        format.json { render json: @courtstation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courtstations/1
  # PUT /courtstations/1.json
  def update
    @courtstation = Courtstation.find(params[:id])

    respond_to do |format|
      if @courtstation.update_attributes(params[:courtstation])
        format.html { redirect_to @courtstation, notice: 'Courtstation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @courtstation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courtstations/1
  # DELETE /courtstations/1.json

def redirect_to_station_path
    case current_user.station
when "milimani family" then redirect_to 'http://10.66.110.15:81/courtstations/1/casefiles'



end
end
end

app/helpers/courtstations_helper.rb
module CourtstationsHelper
end

app/views/courtstations/_form.html.erb
<%= form_for(@courtstation) do |f| %>
  <% if @courtstation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@courtstation.errors.count, "error") %> prohibited this courtstation from being saved:</h2>

      <ul>
      <% @courtstation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :typeofcourt %><br />
    <%= f.text_field :typeofcourt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courtstations/edit.html.erb
<h1>Editing courtstation</h1>

<%= render 'form' %>

<%= link_to 'Show', @courtstation %> |
<%= link_to 'Back', courtstations_path %>

app/views/courtstations/index.html.erb
<h1>Listing courtstations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Typeofcourt</th>
    <th></th>
<th></th>
    <th></th>
<th></th>
   
  </tr>

<% @courtstations.each do |courtstation| %>
  <tr>
    <td><%= courtstation.name %></td>
    <td><%= courtstation.typeofcourt %></td>
  
<td><%= link_to 'cases',  courtstation_casefiles_path(courtstation.id)%></td>
 
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Courtstation', new_courtstation_path %>

app/views/courtstations/new.html.erb
<h1>New courtstation</h1>

<%= render 'form' %>

<%= link_to 'Back', courtstations_path %>

app/views/courtstations/search.html.erb
<div id = "searchform" >
<%= search_form_for @q ,url: courtstationmovements_courtstation_path do |f|%>
  <div class="field">
 <%= f.label :recordcreatedby_cont ,"Staff" %><br />
    <%= f.text_field :recordcreatedby_cont , :Placeholder => "Search by Staff"%>
  </div>
<div class="field">
 <%= f.label :officer_cont ,"Officer Name" %><br />
    <%= f.text_field :officer_cont , :Placeholder => "Search by Officer"%>
  </div>
<div class="field">
    <%= f.label :takenby_cont ,"Taken by" %><br />
    <%= f.text_field :takenby_cont , :Placeholder => "Search by Taken by"%>
  </div>
<div class="field">
    <%= f.label :date_eq ,"Date Out" %><br />
    <%= f.text_field :date_eq , :Placeholder => "Search by Date out YYYY-MM-DD"%>
  </div>
 <div class="actions"><%= f.submit %></div> 
<% end %>
</div>

app/views/courtstations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @courtstation.name %>
</p>

<p>
  <b>Type of court:</b>
  <%= @courtstation.typeofcourt %>
</p>


<%= link_to 'Edit', edit_courtstation_path(@courtstation) %> 
<%= link_to 'Back', courtstations_path %>

app/views/courtstations/stationmovements.erb
	<div id = "searchform" >
	<%= search_form_for @q ,url: station_path do |f|%>
	 <div class="field">
	    <%= f.label :category_cont ,"Category" %><br />
	    <%= f.select :category_cont,Movement.options_for_category ,:include_blank => true%>
	  </div>
	 <div class="field">
	    <%= f.label :officer_cont ,"Officer Taking Action" %><br />
	    <%= f.text_field:officer_cont, :Placeholder => "Type The Officer Name Here" %>
	  </div>
	 <div class="field">
	    <%= f.label :to_cont ,"File Taken To" %><br />
	    <%= f.text_field:to_cont, :Placeholder => "Type The Destination Here" %>
	  </div>
	 <div class="field">
	    <%= f.label :date_cont ,"Date Taken" %><br />
	    <%= f.text_field:date_cont, :Placeholder => "Date Taken yyyy-mm-dd" %>
	  </div>


	 <div class="actions"><%= f.submit %></div>
	<% end %>
<table id= "movements" class = "display" >
<thead>
  <tr>

<th>Category</th>   
  <th>Case Number</th>  
<th>Date</th>
    <th>From</th>
    <th>To</th>
<th>Officer</th>
    <th>Taken by</th>
    <th>Reason</th>
    <th>Results</th>
    <th>Results Date</th>
 
    <th>Datein</th>
    <th>Remarks</th>
	<th>Telephone Number</th>
    <th>Edit</th>
    <th>Show</th>

  </tr>
</thead>
<tbody>
<% @stationmovements.each do |movement| %>
  <tr>
  <td><%=movement.category%></td>
    <td><%=movement.casefile.casenumber%></td>
<td><%= movement.date %></td>
    <td><%= movement.from %></td>
    <td><%= movement.to %></td>
<td><%= movement.officer %></td>
    <td><%= movement.takenby %></td>
    <td><%= movement.reason %></td>
    <td><%= movement.results %></td>
    <td><%= movement.dateofresult %></td>
   
    <td><%= movement.datein %></td>
    <td><%= movement.remarks %></td>
  <td><%= movement.tel %></td>
    <td><%= link_to 'Edit', edit_courtstation_casefile_movement_path(movement.casefile.courtstation,movement.casefile, movement)%></td>
 <td><%= link_to 'Show', courtstation_casefile_movement_path(movement.casefile.courtstation,movement.casefile, movement)%></td>
  </tr>
<% end %>
</tbody>
</table>
<div id = "dashboardicons" >
<%= link_to link_to image_tag('/assets/all.png') + 'Cases', courtstation_casefiles_path(params[:id]) %>
</div>