config/routes.rb
Case::Application.routes.draw do

scope 'tracks' do

resources :courtstations do
resources :batches
end

resources :sms

get 'courtstations:id', to: 'courtstations#stationmovements', as: :station

resources :courtstations do
  resources :casefiles do
 collection do
    match 'search' => 'casefiles#search', via: [:get, :post], as: :search
  end
    resources :movements do
  end
end
end

  devise_for :users

  resources :judicial_officers

  devise_for :admins

  get "dashboard/audit"
get "dashboard/login"
get "admin/index"
get "dashboard/index"
get "dashboard/useractivity"
get "dashboard/mini_dashboard"
get "dashboard/caselistreport"
get "dashboard/casestatusreports"

   
 root :to => 'courtstations#index'

end
end

app/models/casefile.rb
class Casefile < ActiveRecord::Base
before_save :set_copied_flag,:if => :new_record? 
# Has many movements

has_many :movements

# Belongs to a particular station

belongs_to :courtstation

# Read and write the following fields;
 attr_accessible :casenumber, :caseindex,:deathcertnumber,:deathcertserial,:casestatus, :approvaldate,:gazettenoticedate,:objectiondate,:grantissueddate, :grantconfirmeddate, :datelastincourt, :dateoffilling, :parties_names,:parties_names_b,:deceasedcitizenship,:deceasedresidence,:deceasedplaceofdeath,:deceaseddateofdeath,:remarks, :natureofclaim, :yearfiled,:mobile_num,:recordcreatedby,:recordupdatedby
 
# Require the Presence of the following;

validates :casenumber ,:presence => true ,:length => { :minimum => 5 }

# validates :dateoffilling,:presence => true

validates :yearfiled,:presence => true,:length => { :minimum => 4 }

# validates :typeofcase,:presence => true,:length => { :minimum => 3 }

validates :parties_names,:presence => true,:length => { :minimum => 10 } # To change to deceasedname

validates :natureofclaim,:presence => true,:length => { :minimum => 2 }

# Death Certificate serial number Must be included;

#validates :deathcertserial,:presence => true ,:length => { :minimum => 5 }#,:message => "You Must Include Death Cerificate Serial Number"

# Death Certificate Number Must be included;

#validates :deathcertnumber ,:presence => true ,:length => { :minimum => 5 }#,:message => "You Must Include Death Cerificate Number"

# Hack to  Load empty (Prevent Pulling of all records)Table at the Loading of Index Page;

scope :none, lambda { where(:id => -1)}

def set_copied_flag
 self.copied_flag = 1
end

def self.station_records
a = Casefile.where(courtstation_id: User.current_user.courtstation_id)
end

def casenumber_deceasedname
"#{casenumber} - #{parties_names}"
end

end

app/controllers/casefiles_controller.rb
class CasefilesController < ApplicationController
before_filter :authenticate_user!
  # GET courtstations/1/casefiles
  # GET courtstations/1/casefiles.json

def index
    @courtstation = Courtstation.find(params[:courtstation_id])
    @case1 = @courtstation.casefiles
 	if params[:q].blank?
	@q = @case1.none.ransack # so you have a ransack search
	else
	@q = @case1.ransack(params[:q])
	end
	@casefiles = @q.result

	    respond_to do |format|
	      format.html # index.html.erb
	      format.json { render :json => @casefiles }
	    end
  end

  # GET courtstations/1/casefiles/1
  # GET courtstations/1/casefiles/1.json
  def show
    @courtstation = Courtstation.find(params[:courtstation_id])
    @casefile = @courtstation.casefiles.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @casefile }
    end
  end

  # GET courtstations/1/casefiles/new
  # GET courtstations/1/casefiles/new.json
  def new
    @courtstation = Courtstation.find(params[:courtstation_id])
    @casefile = @courtstation.casefiles.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @casefile }
    end
  end

  # GET courtstations/1/casefiles/1/edit
  def edit
    @courtstation = Courtstation.find(params[:courtstation_id])
    @casefile = @courtstation.casefiles.find(params[:id])
  end

  # POST courtstations/1/casefiles
  # POST courtstations/1/casefiles.json
  def create
    @courtstation = Courtstation.find(params[:courtstation_id])
    @casefile = @courtstation.casefiles.build(params[:casefile])

    respond_to do |format|
      if @casefile.save
        format.html { redirect_to([@casefile.courtstation, @casefile], :notice => 'Casefile was successfully created.') }
        format.json { render :json => @casefile, :status => :created, :location => [@casefile.courtstation, @casefile] }
      else
        format.html { render :action => "new" }
        format.json { render :json => @casefile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT courtstations/1/casefiles/1
  # PUT courtstations/1/casefiles/1.json
  def update
    @courtstation = Courtstation.find(params[:courtstation_id])
    @casefile = @courtstation.casefiles.find(params[:id])

    respond_to do |format|
      if @casefile.update_attributes(params[:casefile])
        format.html { redirect_to([@casefile.courtstation, @casefile], :notice => 'Casefile was successfully updated.') }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @casefile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE courtstations/1/casefiles/1
  # DELETE courtstations/1/casefiles/1.json
  def destroy
    @courtstation = Courtstation.find(params[:courtstation_id])
    @casefile = @courtstation.casefiles.find(params[:id])
    @casefile.destroy

    respond_to do |format|
      format.html { redirect_to courtstation_casefiles_url(courtstation) }
      format.json { head :ok }
    end
  end
end

app/helpers/case_files_helper.rb
module CaseFilesHelper
end

app/helpers/casefiles_helper.rb
module CasefilesHelper
end

app/views/casefiles/_form.html.erb
<%= form_for([@casefile.courtstation, @casefile]) do |f| %>
  <% if @casefile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@casefile.errors.count, "error") %> prohibited this casefile from being saved:</h2>

      <ul>
      <% @casefile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
    <%= f.label :'Case Number' %><br />
    <%= f.text_field(:casenumber,:Placeholder => "Type The File Number Here" )%>
  </div>
  <div class="field">
    <%= f.label :'Date of Filling' %><br />
    <%= f.date_select :dateoffilling ,:include_blank => true, :order => [:day, :month, :year]%>
  </div>
   <div class="field">
    <%= f.label :'Year of Filling' %><br />
    <%= f.text_field :yearfiled ,:Placeholder => "Year of Filling"%>
  </div>

  <div class="field">
    <%= f.label :'Type of Case' %><br />
    <%= f.text_field:typeofcase ,:value=> "Probate and Administration"%>
  </div>
 
  <div class="field">
   <%= f.label :"Deceased Name" %><br />
   <%= f.text_area :parties_names,:size => "24x3",:Placeholder => "Deceased Name"%>
  </div>
  <div class="field">
   <%= f.label :"Death Serial Number" %><br />
   <%= f.text_field :deathcertserial,:Placeholder => "Death Certificate Serial Number"%>
  </div>
  <div class="field">
   <%= f.label :"Death Certificate Number" %><br />
   <%= f.text_field :deathcertnumber,:Placeholder => "Death Certificate Number"%>
  </div>
  <div class="field">
   <%= f.label :"Deceased Citizenship" %><br />
   <%= f.text_field :deceasedcitizenship,:value =>"Kenyan"%>
  </div>
  <div class="field">
   <%= f.label :"Deceased Residence" %><br />
   <%= f.text_field :deceasedresidence,:Placeholder => "Deceased Place of Residence"%>
  </div>
 <div class="field">
   <%= f.label :"Deceased Place of Death" %><br />
   <%= f.text_field :deceasedplaceofdeath,:Placeholder => "Deceased Place of Death"%>
  </div>
 <div class="field">
   <%= f.label :"Deceased Date of Death" %><br />
   <%= f.date_select :deceaseddateofdeath,start_year:Date.current.year, end_year:1970,:include_blank => true, :order => [:day, :month, :year]%>
  </div>
  <div class="field">
    <%= f.label :'Petitioners' %><br />
    <%= f.text_area :parties_names_b, :size => "24x3",:Placeholder => "Type the Petitioners Names and Adddress "%>
  </div>
 <div class="field">
    <%= f.label :'Nature of Claim' %><br />
    <%= f.text_area :natureofclaim, :size => "24x3",:value => "SUCCESSION"%>
  </div>
  <div class="field">
   <%= f.label :'Grant Approval Date' %><br />
   <%= f.date_select :approvaldate,start_year:Date.current.year, end_year:1970,:include_blank => true, :order => [:day, :month, :year]%>
  </div>
  <div class="field">
   <%= f.label :'Grant Was Gazzeted' %><br />
   <%= f.date_select :gazettenoticedate,start_year:Date.current.year, end_year:1970,:include_blank => true, :order => [:day, :month, :year]%>
  </div>
  <div class="field">
    <%= f.label :'Date Objection was Filed' %><br />
    <%= f.date_select:objectiondate,start_year:Date.current.year, end_year:1970,:include_blank => true%>
  </div>
  <div class="field">
   <%= f.label :'Date Grant Was Issued' %><br />
   <%= f.date_select :grantissueddate,start_year:Date.current.year, end_year:1970,:include_blank => true, :order => [:day, :month, :year]%>
  </div>
  <div class="field">
    <%= f.label :'Date Grant Was Confirmed' %><br />
    <%= f.date_select :grantconfirmeddate,start_year:Date.current.year, end_year:1970,:include_blank => true, :order => [:day, :month, :year]%>
  </div>

  <div class="field">
    <%= f.label :Remarks %><br />
    <%= f.text_area:remarks, :size => "24x2" ,:Placeholder => "Type any  other useful informatin relevant to the file"%>
</div>
<div class="field">
    <%= f.label :'Mobile Number' %><br />
    <%= f.text_field :mobile_num,:Placeholder => "Separate Multiple Numbers by Comma" %>
  </div>

 <div class="field">
 <%= f.hidden_field :recordupdatedby, :value =>current_user.username,:readonly => true %>
 </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/casefiles/edit.html.erb
<h1>Editing casefile</h1>

<%= render 'form' %>

<%= link_to 'Show', [@casefile.courtstation, @casefile] %> |
<%= link_to 'Back', courtstation_casefiles_path(@casefile.courtstation) %>

<div id = "dashboardicons" >
<%= link_to link_to image_tag('/assets/show.png') + 'Show', [@casefile.courtstation, @casefile] %>
<%= link_to link_to image_tag('/assets/back.jpeg') + 'Back',  courtstation_casefiles_path(@casefile.courtstation) %>
</div>

app/views/casefiles/index.html.erb
	<h1>Listing Files For <%=@courtstation.name%></h1>
	<div id = "searchform" >
	<%= search_form_for @q ,url: courtstation_casefiles_path do |f|%>
	 <div class="field">
	    <%= f.label :casenumber_cont ,"Case Number" %><br />
	    <%= f.text_field :casenumber_cont , :Placeholder => "Search by Case Number"%>
	  </div>
	<div class="field">
	    <%= f.label :parties_names_cont ,"Party Name" %><br />
	    <%= f.text_field :parties_names_cont , :Placeholder => "Search by Parties"%>
	  </div>
	<div class="field">
	    <%= f.label :yearfiled_eq ,"Year Filed" %><br />
	    <%= f.text_field :yearfiled_eq, :Placeholder => "Search by Year"%>
	  </div>
	 <div class="actions"><%= f.submit %></div>
	<% end %>
	</div>
	<table id= "casefiles" class = "display" >
	<thead>
  	<tr>
   	<th>Case Index</th>   
	<th>Case Number</th>
	<th>Date Grant was Approved</th>
	<th>Deceased Name</th>
	<th>Death Cert Serial</th>
	<th>Death Cert Number</th>
         <th>Petitioners/Address</th>
    	<th>Nature of Claim</th>
   	<th>Date of Gazzetment</th>
	<th>Date of Objection</th>
        <th>Date Grant was Issued</th>
        <th>Date Grant was Confirmed</th>
    	<th>Remarks</th>
	<th>Mobile Number</th>
    	<th>Show</th>
    	<th>Movements</th>
 	<th>Edit</th>
  	</tr>
	</thead>
	<tbody>
	<% @casefiles.each do |casefile| %>
  	<tr>
  	<td><%= casefile.caseindex %></td>
    	<td><%= casefile.casenumber %></td>
    	<td><%= casefile.approvaldate%></td>
    	<td><%= casefile.parties_names %></td>
 	<td><%= casefile.deathcertserial %></td>
 	<td><%= casefile.deathcertnumber %></td>
   	<td><%= casefile.parties_names_b %></td>
    	<td><%= casefile.natureofclaim %></td>
        <td><%= casefile.gazettenoticedate %></td>
	<td><%= casefile.objectiondate %></td>
        <td><%= casefile.grantissueddate %></td>
        <td><%= casefile.grantconfirmeddate %></td>
    	<td><%= casefile.remarks %></td>
  	<td><%= casefile.mobile_num %></td>
 
    	<td><%= link_to 'Show', [casefile.courtstation, casefile] %></td>
	<td><%= link_to 'movements',courtstation_casefile_movements_path(casefile.courtstation,casefile)%></td>
    	<td><%= link_to 'Edit', edit_courtstation_casefile_path(casefile.courtstation, casefile) %></td>

  </tr>
<% end %>
</table>
</tbody>
</table>
<br />
<div id = "dashboardicons" >
<%= link_to image_tag('/assets/add.png') + "New Probate and Administration File", new_courtstation_casefile_path(params[:courtstation_id]) %>
<%= link_to image_tag('/assets/filemovement.png') + "All File Movements",station_path(params[:courtstation_id]) %>
<%= link_to image_tag('/assets/sms.png') + "View Sent SMS",sms_path %>
<%= link_to image_tag('/assets/archive.png') + "Batches",courtstation_batches_path(params[:courtstation_id]) %>
</div>

app/views/casefiles/new.html.erb
<h1>New Probate and Administration Case</h1>

<%= render 'form' %>

<div id = "dashboardicons" >
<%= link_to link_to image_tag('/assets/back.jpeg') + 'Back',  courtstation_casefiles_path(@casefile.courtstation) %>
</div>

app/views/casefiles/search.html.erb
<h2>Welcome</h2>
<div id = "dashboard" >


<p>Type the Case Number Here<p/>
<%= image_tag "search.png" %>
<%= search_form_for @q do |f| %>

  # Search if the name field contains...
  <%= f.label :casenumber_cont %>
  <%= f.search_field :casenumber_cont %>


  <%= f.submit %>
<% end %>
<div id = "dashboardicons" >


<%= link_to image_tag('/assets/caseregister.png') + 'Cases Register'%>
<%= link_to image_tag('/assets/filemovement.png') + 'File Movements'%>
<%= link_to image_tag('/assets/casestatus.png') + 'Case Status'%>

<%= link_to image_tag('/assets/user.png') + 'User Activity'%>
<%= link_to image_tag('/assets/audit.png') + 'Audit Trail'%>


</div>

</div>

app/views/casefiles/show.html.erb
<table border ="1" cellpadding="1" cellspacing="5" >
<tr>
  <td><b>Case number:</b></td>
  <td><%= @casefile.casenumber %></td>
</tr>

<tr>
  <td><b>Date of filling:</b></td>
  <td><%= @casefile.dateoffilling %></td>
</tr>

<tr>
  <td><b>Court station:</b></td>
  <td><%= @casefile.courtstation.name %></td>
</tr>

<tr>
  <td><b>Deceased<b> </td>
  <td><%=@casefile.parties_names%> </td>
</tr>
<tr>
  <td><b>Deceased Citizenship<b> </td>
  <td><%=@casefile.deceasedcitizenship%> </td>
</tr>
<tr>
  <td><b>Deceased Residence<b> </td>
  <td><%=@casefile.deceasedresidence%> </td>
</tr>

<tr>
  <td><b>Deceased Place of Death<b> </td>
  <td><%=@casefile.deceasedplaceofdeath%> </td>
</tr>
<tr>
  <td><b>Deceased Date of Death<b> </td>
  <td><%=@casefile.deceaseddateofdeath%> </td>
</tr>
<tr>
  <td><b>Petitioners<b> </td>
  <td><%=@casefile.parties_names_b%> </td>
</tr>

<tr>
<td><b>Type of Case<b></td> 
<td><%=@casefile.typeofcase%> </td>
</tr>

<tr>
 <td> <b>Nature of claim:</b></td>
 <td> <%= @casefile.natureofclaim %></td>
</tr>

<tr>
 <td> <b>Date Grant was Approved:</b></td>
 <td><%= @casefile.approvaldate %></td>
</tr>
<tr>
 <td> <b>Date Grant Was Gazzeted:</b></td>
 <td><%= @casefile.gazettenoticedate %></td>
</tr>
<tr>
 <td> <b>Date of Objection:</b></td>
 <td><%= @casefile.objectiondate %></td>
</tr>

<tr>
 <td> <b>Date Grant Was Issued:</b></td>
 <td><%= @casefile.grantissueddate %></td>
</tr>
<tr>
 <td> <b>Date Grant Was Confirmed:</b></td>
 <td><%= @casefile.grantconfirmeddate %></td>
</tr>
<tr>
<td><b>Remarks:</b></td>
<td> <%= @casefile.remarks %> </td>
</tr>

<tr>
<td><b>Mobile Number:</b></td>
<td> <%= @casefile.mobile_num %></td>
</tr>
</table>

<div id = "dashboardicons" >
<%= link_to link_to image_tag('/assets/edit.png') + 'Edit', edit_courtstation_casefile_path(@casefile.courtstation, @casefile) %>
<%= link_to link_to image_tag('/assets/back.jpeg') + 'Back',  courtstation_casefiles_path(@casefile.courtstation) %>
<%= link_to link_to image_tag('/assets/add.png') + 'New Movement', new_courtstation_casefile_movement_path(@casefile.courtstation, @casefile) %>
</div>